server:
  port: 8084

spring:
  application:
    name : dataIn-survey

  config:
    import: "optional:configserver:"


  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: dataIn-config-server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/