server:
  port: 8081

spring:
  application:
    name : dataIn-ahp
  config:
    import: "optional:configserver:http://localhost:8888"

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: dataIn-config-server

#Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/